/*
Deployment script for Northwind_v1.0

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "Northwind_v1.0"
:setvar DefaultFilePrefix "Northwind_v1.0"
:setvar DefaultDataPath "C:\Users\uladzislau_karpovich\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\mssqllocaldb\"
:setvar DefaultLogPath "C:\Users\uladzislau_karpovich\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\mssqllocaldb\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating [dbo].[EmployeeCreditCards]...';


GO
CREATE TABLE [dbo].[EmployeeCreditCards] (
    [CardNumber] NVARCHAR (50) NOT NULL,
    [CardHolder] NVARCHAR (50) NULL,
    [ExpireDate] DATETIME      NOT NULL,
    [EmployeeID] INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([CardNumber] ASC)
);


GO
PRINT N'Creating [dbo].[FK_EmployeeCard_Employee]...';


GO
ALTER TABLE [dbo].[EmployeeCreditCards] WITH NOCHECK
    ADD CONSTRAINT [FK_EmployeeCard_Employee] FOREIGN KEY ([EmployeeID]) REFERENCES [dbo].[Employees] ([EmployeeID]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[EmployeeCreditCards] WITH CHECK CHECK CONSTRAINT [FK_EmployeeCard_Employee];


GO
PRINT N'Update complete.';


GO
