/*
Deployment script for Northwind_v1.1

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "Northwind_v1.1"
:setvar DefaultFilePrefix "Northwind_v1.1"
:setvar DefaultDataPath "C:\Users\uladzislau_karpovich\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\mssqllocaldb\"
:setvar DefaultLogPath "C:\Users\uladzislau_karpovich\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\mssqllocaldb\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
/*
Table [dbo].[Region] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[Region])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
PRINT N'Dropping [dbo].[FK_Territories_Region]...';


GO
ALTER TABLE [dbo].[Territories] DROP CONSTRAINT [FK_Territories_Region];


GO
PRINT N'Dropping [dbo].[Region]...';


GO
DROP TABLE [dbo].[Region];


GO
PRINT N'Altering [dbo].[Customers]...';


GO
ALTER TABLE [dbo].[Customers]
    ADD [EstablishDate] DATETIME NULL;


GO
PRINT N'Creating [dbo].[Regions]...';


GO
CREATE TABLE [dbo].[Regions] (
    [RegionID]          INT        NOT NULL,
    [RegionDescription] NCHAR (50) NOT NULL,
    CONSTRAINT [PK_Region] PRIMARY KEY NONCLUSTERED ([RegionID] ASC)
);


GO
PRINT N'Refreshing [dbo].[Customer and Suppliers by City]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[Customer and Suppliers by City]';


GO
PRINT N'Refreshing [dbo].[Invoices]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[Invoices]';


GO
PRINT N'Refreshing [dbo].[Orders Qry]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[Orders Qry]';


GO
PRINT N'Refreshing [dbo].[Quarterly Orders]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[Quarterly Orders]';


GO
PRINT N'Refreshing [dbo].[Sales Totals by Amount]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[Sales Totals by Amount]';


GO
PRINT N'Refreshing [dbo].[CustOrderHist]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[CustOrderHist]';


GO
PRINT N'Update complete.';


GO
